version: "3.8"

services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend:${VERSION}
    container_name: sausage-store-backend
    environment:
      SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
      SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL
      SPRING_DATA_MONGODB_URI: $SPRING_DATA_MONGODB_URI
    networks:
      - sausage-store
  backend-report:
    image: ${CI_REGISTRY_IMAGE}/sausage-backend-report:${VERSION}
    container_name: sausage-store-backend-report
    environment:
      DB: $SPRING_DATA_MONGODB_URI
      PORT: $PORT
    networks:
      - sausage-store
  frontend:
    image: ${CI_REGISTRY_IMAGE}/sausage-frontend:${VERSION}
    container_name: sausage-store-frontend
    ports:
      - "8080:80"
    networks:
      - sausage-store

networks:
  sausage-store: