build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/*
  cache:
    paths:
      - $CI_PROJECT_DIR/.m2/repository
  script:
    - cd backend
    - mvn package
  after_script:
    - echo "JOB_NAME=$CI_JOB_NAME" >> job.env
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    reports:
      dotenv: job.env

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  script:
    - mvn -e verify sonar:sonar -Dsonar.qualitygate.wait=true
  allow_failure: true

include:
  - template: Security/SAST.gitlab-ci.yml

spotbugs-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: $CI_PROJECT_DIR/.m2/repository # не забудьте при сборке также указывать эту папку через аргумент -Dmaven.repo.local
    
telegram-notification-backend:
  stage: notify
  only:
    changes:
    - backend/*
    variables:
    - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\": \"-1002042084305\", \"text\": \"Backend is ready. Artefact - ${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_SHA}/download?job=${JOB_NAME}
  \" }" https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage'
  needs:
    - build-backend-code-job
